### ISSUE TITLE
Word, Sentence, Thought structures - howto?

### ISSUE THREAD

**Issue by qvqc** [sumpygump/sitelen-sitelen#2]
Is there any documentation on writing with this glyph style?  I don't understand the nonlinear container format.  I found this link https://www.jonathangabel.com/archive/2012/t47_lesson_01.html but it seems to be dead for me.

Thanks for any info!

**Comment by sumpygump** [comment]
Hi qvqc, have you checked out this? https://www.jonathangabel.com/toki-pona/

Specifically I think you are asking about this lesson: https://www.jonathangabel.com/toki-pona/lesson-4b/

Let me know if that helps.

**Comment by qvqc** [comment]
Exactly!  

Pona :+1:
